{% set name = "molightning" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SCMusson/molightning/archive/v{{ version }}.tar.gz
  sha256: c92b1de02179998490d3e270b71185ef05ef45f97fa5e4b13338723cea067f2a


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - __unix
    - python >=3.6
    - numpy
    - pytorch
    - pytorch-lightning
    - molearn
    - biobox
    - openmm
    - mdtraj
test:
  imports:
    - molightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SCMusson/molightning
  license_file: LICENSE
  license: GPL-3.0-only
  summary: Molightning accelerates Molearn which contains methods to train neural networks on ensembles of molecular conformations
  description: |
    This software trains a generative neural network on an ensemble of molecular conformations (typically
    obtained by molecular dynamics). The trained model can be used to generate new, plausible
    conformations repesentative of poorly sampled transition states.
  doc_url: https://github.com/SCMusson/molightning
  dev_url: https://github.com/SCMusson/molightning

extra:
    recipe-maintainers:
        - SCMusson
